language: python
python:
# Pypy only implements Python 3.2, which does not have `yield from` syntax.
#  - "pypy3"
  - "3.3"
  - "3.4"
#  - "3.5"
install:
  - sudo apt-get install libxml2-dev libxslt1-dev
  - pip install -r requirements.txt
script:
  - make -k -j`nproc`
